ci_service: travis_ci
coverage_service: coveralls
xcodeproj: Initializable.xcodeproj
workspace: Initializable.xcworkspace
scheme: Initializable
source_directory: Initializable
ignore:
  - Pods/*
  - ../*
